spring.application.name=MicroCesta
server.port=8082

# Configuración básica de H2 en memoria
spring.datasource.url=jdbc:h2:mem:CestaBD
spring.datasource.driverClassName=org.h2.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update

# Registro en Eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka