
spring.application.name=MicroParroco
server.port=8081
spring.datasource.url=jdbc:h2:file:./data/ParrocoDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver

# Agrega esta línea para que se creen las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Es una buena práctica agregar también las credenciales por defecto de H2
spring.datasource.username=sa
spring.datasource.password=