spring.application.name=VentaBoletos
server.port=8081

# Base de datos H2 en memoria para que todos los boletos
# se borren automáticamente cada vez que se detiene la aplicación.
spring.datasource.url=jdbc:h2:mem:boletosdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true